name: "Node Server"
version: "1.0.0"
slug: "node_server"
description: "Простой Node.js сервер, запущенный как аддон"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
options: {}
schema: {}
init: false
ports:
  3000/tcp: 3000
