name: "PostgreSQL Server"
description: "Custom PostgreSQL add-on for Home Assistant"
version: "1.0.2"
slug: "custom_postgres"
init: false
startup: services
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - data:rw
ports:
  5432/tcp: 5432
options:
  database: "ha_db"
  username: "ha_user"
  password: "ha_pass"
schema:
  database: str
  username: str
  password: str
