name: PostgreSQL Server
version: "1.0.0"
slug: postgresql_server
description: PostgreSQL сервер для Home Assistant
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
options:
  database: ha_db
  username: ha_user
  password: secure_password
  pgdata: /data/postgresql
schema:
  database: str
  username: str
  password: str
  pgdata: str
ports:
  5432/tcp: 5432
map:
  - data:rw
host_network: false
privileged: false
full_access: false
