name: "PostgreSQL Server"
description: "Custom PostgreSQL add-on for Home Assistant"
version: "1.0.0"
slug: "custom_postgresql"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
map:
  - data:rw
options:
  database: "ha_db"
  username: "ha_user"
  password: "ha_pass"
schema:
  database: str
  username: str
  password: str
