name: "PostgreSQL Server"
description: "PostgreSQL сервер как аддон для Home Assistant"
version: "1.0.0"
slug: "postgresql_server"
init: false
startup: services
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  database: "ha_db"
  username: "ha_user"
  password: "ha_pass"
schema:
  database: str
  username: str
  password: str
